#!/bin/sh

set -e

if [ "$1" = "configure" ]; then
    update-alternatives --install /usr/bin/js js /usr/bin/node 200 \
                        --slave /usr/share/man/man1/js.1 js.1 /usr/share/man/man1/nodejs.1
fi

/usr/lib/node_modules/npm/scripts/relocate.sh /usr/bin/nodejs

#DEBHELPER#
